# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install --production --ignore-scripts

# Copy app source
COPY . .

# Expose port if needed (not required for stdio-based MCP)

# Command to run the MCP server
CMD [ "npm", "start" ]
